@startuml
!include_many ./data-management-style.txt

rectangle "Example RO-Crate Metadata Document(s) from a domain" as docs


rectangle "RO-Crate Schema Tools" as tools {
rectangle "Schema.org Schema" as sos
rectangle "RO-Crate Schema additions" as roc
rectangle "Tool: rocsoss script" as rocsoss
}

rectangle "Domain-Specific Mode File" as mod
rectangle "Domain-Specific SOSS" as dssoss
sos -down-> rocsoss : input 
roc -down-> rocsoss : input

docs --down--> rocsoss

rocsoss -down-> mod : Generate

rocsoss .down.> dssoss : Optional: Generate 

note bottom of mod : Contains Classes and Properties representing\nthe intersection of the example(s) and\nSchema.org/RO-Crate entities
note bottom of dssoss : Domain-Specific\nSchema.org Style Schema
@enduml