@startuml
!include_many ./data-management-style.txt

title: The three main components for RO-Crate editing with Crate-O


rectangle "1. Schema.org Style Schema for Domain" <<standards>> as soss



note top of soss: Eg Language Data Commons terms\nsuch as communicationMode, SpokenLanguage

rectangle "2. Domain-specific Mode" <<workspace>> as md
note top of md: Eg Language Data Commons\nmode file
note bottom of md: - Specify behaviour of editor, eg Crate-O\n- Validate RO-Crate structure

rectangle "3. RO-Crate Profile Document" <<standards>> as pf 

pf -left-> md : Show rules\nfrom
soss <-right- md : Based on

note top of pf: Eg Language Data Commons RO-Crate\nProfile Document
@enduml